@echo off
echo Initializing Git repository...
git init
echo Adding all files...
git add .
echo Creating initial commit...
git commit -m "Initial commit"
echo Adding remote repository...
git remote add origin https://github.com/jiangwei6/key.git
echo Pushing to main branch...
git push -u origin main
echo Done!
pause 