[build]
builder = "nixpacks"
buildCommand = "npm run build"
watchPatterns = ["client/**/*", "server/**/*"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "always"

[deploy.envs]
NODE_ENV = "production"
CI = "false" 