[build]
builder = "nixpacks"
buildCommand = "npm run install && npm run client-install && npm run client-build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "always"

[deploy.envs]
NODE_ENV = "production"
CI = "false"
PORT = "5000"